type: object
x-stoplight:
  id: ktth5ebdoqxyq
description: |-
  Seapim product that groups one or more API proxies.

  A record is uniquely identified by seapimOrg + productName combined
required:
  - id
  - seapimOrg
  - productName
  - createdAt
  - updatedAt
  - consumers
  - productProxies
properties:
  id:
    $ref: ../models/Id.yaml
    x-stoplight:
      id: uga1ets445vml
    description: Database identifier
  seapimOrg:
    $ref: ./SEAPIM Org.yaml
    x-stoplight:
      id: h9apa39ycpd64
    description: SEAPIM platform organisation name
  productName:
    type: string
    x-stoplight:
      id: 6k7jrq9ow0r2t
    example: Product-SE API Managment
    description: Product name
  callRate:
    type: integer
    x-stoplight:
      id: 6bihm2ijuwjw9
    description: 'Allocated maximum number of API calls allowed per minute, converted from actual SEAPIM quota configuation which may be defined using a different time unit'
    example: 600
  quota:
    type: integer
    x-stoplight:
      id: d12uoql2ekfnb
    description: 'SEAPIM quota number, first part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 1000
  quotaInterval:
    type: integer
    x-stoplight:
      id: pa9s4jaf2wc6j
    description: 'SEAPIM quota interval, second part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 2
  quotaTimeunit:
    $ref: ./Quota Time Unit.yaml
    x-stoplight:
      id: mynbrsmgelmtz
    description: 'SEAPIM quota time unit, third part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
  scopes:
    type: array
    x-stoplight:
      id: dkc8polvkdqxm
    description: 'List of API scopes which grant conditional access to specified API, using partial matching of operations by a string in the endpoint path'
    items:
      x-stoplight:
        id: f1vzdvnc9ps0x
      type: string
      example: 'urn:API-Metadata-V2:*:read, urn:API-Metadata-V2:apis:write"'
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: oc3ivzd73ig0u
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: zb9qjrdrviidr
  consumers:
    type: array
    x-stoplight:
      id: o6hh9a6t63p7d
    description: List of application consumers with a subscription that refers to this product
    items:
      $ref: ./Consumer.yaml
      x-stoplight:
        id: io1ji4hafwjw3
  productProxies:
    type: array
    x-stoplight:
      id: znu9q9to5qqn6
    description: List of API proxies included in this product
    items:
      $ref: ./Product Proxy.yaml
      x-stoplight:
        id: 4u8ligdiae28v
title: Product
