type: object
x-stoplight:
  id: qvzkdns1k3f5q
description: |-
  Seapim product that groups one or more API proxies.

  A record is uniquely identified by seapimOrg + productName combined
required:
  - id
  - seapimOrg
  - productName
  - createdAt
  - updatedAt
  - consumers
  - productProxies
properties:
  id:
    $ref: ../models/Id.yaml
    x-stoplight:
      id: pxmle71879r39
    description: Database identifier
  seapimOrg:
    $ref: ./SEAPIMOrg.yaml
    x-stoplight:
      id: 49ur668jisucf
    description: SEAPIM platform organisation name
  productName:
    type: string
    x-stoplight:
      id: 4sp79tmh43eem
    example: Product-SE API Managment
    description: Product name
  callRate:
    type: integer
    x-stoplight:
      id: bnfayoezcjnva
    description: 'Allocated maximum number of API calls allowed per minute, converted from actual SEAPIM quota configuation which may be defined using a different time unit'
    example: 600
  quota:
    type: integer
    x-stoplight:
      id: qa0b01yag5yuo
    description: 'SEAPIM quota number, first part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 1000
  quotaInterval:
    type: integer
    x-stoplight:
      id: obqlhfs45t79x
    description: 'SEAPIM quota interval, second part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 2
  quotaTimeunit:
    $ref: ./Quota_timeunit.yaml
    x-stoplight:
      id: 87qp7kv1q6gpb
    description: 'SEAPIM quota time unit, third part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
  scopes:
    type: array
    x-stoplight:
      id: 655b5ci5l53u3
    description: 'List of API scopes which grant conditional access to specified API, using partial matching of operations by a string in the endpoint path'
    items:
      x-stoplight:
        id: iq61kby9y7925
      type: string
      example: 'urn:API-Metadata-V2:*:read, urn:API-Metadata-V2:apis:write"'
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: 3k72x23xtdaes
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: uos20dird4lfy
  consumers:
    type: array
    x-stoplight:
      id: bjtyrtwwt52ag
    description: List of application consumers with a subscription that refers to this product
    items:
      $ref: ./Consumer.yaml
      x-stoplight:
        id: a7luee63zayke
  productProxies:
    type: array
    x-stoplight:
      id: e38o2415k23so
    description: List of API proxies included in this product
    items:
      $ref: ./ProductProxy.yaml
      x-stoplight:
        id: 10uzcrw0g94qb
title: ''
